#!/bin/bash

### BEGIN INIT INFO
# Provides:          aqua-udp-proxy
# Required-Start:    $remote_fs $syslog network-manager                              
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Aqua UDP Proxy Server
# Description:       Aqua UDP Proxy Server to control Aqua Device
### END INIT INFO

. /lib/lsb/init-functions

NAME=aqua-udp-proxy
JSVC=/usr/bin/jsvc
JAVA_HOME=/usr/java/latest
APP_DIR=/usr/local/apps/aqua
CLASSPATH="\
${APP_DIR}/lib/commons-daemon-1.0.15.jar:\
${APP_DIR}/lib/aqua-connect-1.0.jar:\
${APP_DIR}/lib/jssc-2.6.0.jar:\
${APP_DIR}/lib/slf4j-log4j12-1.7.5.jar:\
${APP_DIR}/lib/args4j-2.0.26.jar:\
${APP_DIR}/lib/log4j-1.2.17.jar:\
${APP_DIR}/lib/slf4j-api-1.7.5.jar:\
${APP_DIR}/aqua-controller.jar"

USER=marek
PIDFILE=/var/run/${NAME}.pid
LOGFILE=/var/log/aqua/${NAME}.log
CLASS=pl.marand.aqua.AquaUDPProxyServer
ARGS="-dev /dev/ttyUSB0"

do_exec()
{
    $JSVC -home "$JAVA_HOME" -cp $CLASSPATH -user $USER -outfile $LOGFILE -errfile $LOGFILE -pidfile $PIDFILE $1 $CLASS ${ARGS}
}

case "$1" in
    start)
	log_action_begin_msg "Starting $NAME daemon";
        do_exec
        rc=$?
        log_action_end_msg ${rc}
            ;;
    stop)
	log_action_begin_msg "Stopping $NAME daemon";
        do_exec "-stop"
        rc=$?
        log_action_end_msg ${rc}
            ;;
    restart)
        if [ -f "$PIDFILE" ]; then
            do_exec "-stop"
            do_exec
        else
            echo "Daemon $NAME is not running."
            start
        fi
            ;;
    status)
    	rc=1
		if [[ -f $PIDFILE ]]; then
		  pid=`cat $PIDFILE`
		  ps -p $pid > /dev/null
		  if [[ $? -eq 0 ]]; then
		    echo "Daemon $NAME is running with PID: `cat $PIDFILE`"
		    rc=0
		  else
		    echo "Daemon $NAME is not running."
		  fi
		else
		  echo "Daemon $NAME is not running."
		fi
		exit ${rc}
	  ;;
    *)
            echo "usage: daemon {start|stop|restart|status}" >&2
            exit 3
            ;;
esac
